// Properties Database
const propertiesData = {
    1: {
        id: 1,
        title: "Modern Luxury Villa",
        type: "Villa",
        status: "Featured",
        price: "9,000,000",
        location: "Emirates Hills, Dubai",
        fullAddress: "Emirates Hills, Al Hebiah Fourth, Dubai",
        bedrooms: 4,
        bathrooms: 3,
        area: "3,200",
        areaUnit: "sq ft",
        floor: "Ground + 1",
        floorsInFlat: 2,
        totalRooms: 7,
        description: "Experience luxury living in this stunning modern villa featuring contemporary design, spacious interiors, and premium finishes throughout. Perfect for families seeking elegance and comfort in Dubai's most prestigious community.",
        heroImage: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=600&fit=crop",
        features: [
            "Private Swimming Pool",
            "Landscaped Garden",
            "Smart Home System",
            "Premium Kitchen Appliances",
            "Walk-in Closets",
            "Home Theater",
            "Maid's Room",
            "Private Parking (4 cars)"
        ]
    },
    2: {
        id: 2,
        title: "Elegant Penthouse Suite",
        type: "Penthouse",
        status: "New",
        price: "6,800,000",
        location: "Downtown Dubai, UAE",
        fullAddress: "Downtown Dubai, Burj Khalifa District",
        bedrooms: 3,
        bathrooms: 2,
        area: "2,800",
        areaUnit: "sq ft",
        floor: "45th Floor",
        floorsInFlat: 1,
        totalRooms: 6,
        description: "This spectacular penthouse offers breathtaking views of the Burj Khalifa and Dubai skyline. Featuring floor-to-ceiling windows, high-end finishes, and access to world-class amenities in the heart of Downtown Dubai.",
        heroImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=600&fit=crop",
        features: [
            "Burj Khalifa Views",
            "Floor-to-ceiling Windows",
            "Concierge Service",
            "Private Elevator",
            "Rooftop Terrace",
            "Premium Gym Access",
            "Valet Parking",
            "24/7 Security"
        ]
    },
    3: {
        id: 3,
        title: "Contemporary Townhouse",
        type: "Townhouse",
        status: "",
        price: "4,400,000",
        location: "Dubai Marina, UAE",
        fullAddress: "Dubai Marina, Marina Promenade",
        bedrooms: 3,
        bathrooms: 2.5,
        area: "2,400",
        areaUnit: "sq ft",
        floor: "Ground + 2",
        floorsInFlat: 3,
        totalRooms: 6,
        description: "Modern townhouse in vibrant Dubai Marina with marina views. Features contemporary design, spacious living areas, and easy access to waterfront dining, shopping, and entertainment.",
        heroImage: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200&h=600&fit=crop",
        features: [
            "Marina Views",
            "Private Terrace",
            "Modern Kitchen",
            "Guest Powder Room",
            "Storage Room",
            "Community Pool",
            "Fitness Center",
            "Secure Parking"
        ]
    },
    4: {
        id: 4,
        title: "Waterfront Apartment",
        type: "Apartment",
        status: "Hot",
        price: "3,500,000",
        location: "Palm Jumeirah, Dubai",
        fullAddress: "Palm Jumeirah, Golden Mile",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,800",
        areaUnit: "sq ft",
        floor: "12th Floor",
        floorsInFlat: 1,
        totalRooms: 4,
        description: "Stunning waterfront apartment on the iconic Palm Jumeirah. Wake up to panoramic sea views, enjoy resort-style living with beach access, and experience the ultimate Dubai lifestyle.",
        heroImage: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=600&fit=crop",
        features: [
            "Sea Views",
            "Private Beach Access",
            "Infinity Pool",
            "Spa & Sauna",
            "BBQ Area",
            "Children's Play Area",
            "Covered Parking",
            "24/7 Concierge"
        ]
    },
    5: {
        id: 5,
        title: "Luxury Estate",
        type: "Villa",
        status: "Featured",
        price: "12,500,000",
        location: "Arabian Ranches, Dubai",
        fullAddress: "Arabian Ranches, Desert Blossom",
        bedrooms: 5,
        bathrooms: 4,
        area: "4,500",
        areaUnit: "sq ft",
        floor: "Ground + 1",
        floorsInFlat: 2,
        totalRooms: 9,
        description: "Magnificent estate in prestigious Arabian Ranches. This palatial villa offers unparalleled luxury with extensive outdoor spaces, premium finishes, and stunning golf course views.",
        heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=600&fit=crop",
        features: [
            "Golf Course Views",
            "Large Swimming Pool",
            "Outdoor Majlis",
            "Chef's Kitchen",
            "Master Suite with Balcony",
            "Home Office",
            "Driver's Room",
            "6-Car Garage"
        ]
    },
    6: {
        id: 6,
        title: "Beachfront Villa",
        type: "Villa",
        status: "New",
        price: "8,200,000",
        location: "Jumeirah Beach, Dubai",
        fullAddress: "Jumeirah Beach Residence (JBR)",
        bedrooms: 4,
        bathrooms: 3.5,
        area: "3,800",
        areaUnit: "sq ft",
        floor: "Ground + 1",
        floorsInFlat: 2,
        totalRooms: 8,
        description: "Exclusive beachfront villa with direct beach access. Enjoy Mediterranean-style architecture, private pool, and stunning Arabian Gulf views in one of Dubai's most sought-after locations.",
        heroImage: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&h=600&fit=crop",
        features: [
            "Direct Beach Access",
            "Private Pool",
            "Sea-facing Balconies",
            "Outdoor Shower",
            "Entertainment Area",
            "Built-in BBQ",
            "Staff Quarters",
            "Private Parking"
        ]
    },
    7: {
        id: 7,
        title: "Garden Villa with Pool",
        type: "Villa",
        status: "",
        price: "7,200,000",
        location: "Emirates Hills, Dubai",
        fullAddress: "Emirates Hills, Lake View",
        bedrooms: 4,
        bathrooms: 3,
        area: "3,500",
        areaUnit: "sq ft",
        floor: "Ground + 1",
        floorsInFlat: 2,
        totalRooms: 7,
        description: "Beautiful villa with lush gardens and lake views. Features elegant interiors, spacious rooms, and a large private pool perfect for family gatherings and entertainment.",
        heroImage: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&h=600&fit=crop",
        features: [
            "Lake Views",
            "Landscaped Gardens",
            "Large Pool",
            "Outdoor Dining",
            "Modern Kitchen",
            "Study Room",
            "Laundry Room",
            "4-Car Parking"
        ]
    },
    8: {
        id: 8,
        title: "Sky View Apartment",
        type: "Apartment",
        status: "Hot",
        price: "5,500,000",
        location: "Downtown Dubai, UAE",
        fullAddress: "Downtown Dubai, Business Bay",
        bedrooms: 3,
        bathrooms: 2,
        area: "2,200",
        areaUnit: "sq ft",
        floor: "38th Floor",
        floorsInFlat: 1,
        totalRooms: 5,
        description: "High-rise apartment with spectacular city and Burj Khalifa views. Modern design with premium finishes, smart home features, and access to 5-star amenities.",
        heroImage: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=600&fit=crop",
        features: [
            "Skyline Views",
            "Smart Home System",
            "Premium Appliances",
            "Balcony",
            "Gym & Pool",
            "Sauna & Steam",
            "Business Center",
            "Valet Service"
        ]
    },
    9: {
        id: 9,
        title: "Modern Condominium",
        type: "Apartment",
        status: "",
        price: "2,800,000",
        location: "Dubai Marina, UAE",
        fullAddress: "Dubai Marina, Marina Gate",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,600",
        areaUnit: "sq ft",
        floor: "22nd Floor",
        floorsInFlat: 1,
        totalRooms: 4,
        description: "Contemporary condo in Dubai Marina with partial sea views. Perfect for young professionals or investors, featuring modern amenities and prime location near metro.",
        heroImage: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=600&fit=crop",
        features: [
            "Partial Sea Views",
            "Open Kitchen",
            "Balcony",
            "Community Pool",
            "Gym Access",
            "Metro Access",
            "Retail Podium",
            "Covered Parking"
        ]
    },
    10: {
        id: 10,
        title: "Luxury Duplex Penthouse",
        type: "Penthouse",
        status: "Featured",
        price: "10,500,000",
        location: "Palm Jumeirah, Dubai",
        fullAddress: "Palm Jumeirah, Tiara Residence",
        bedrooms: 5,
        bathrooms: 4,
        area: "4,200",
        areaUnit: "sq ft",
        floor: "Top Floor",
        floorsInFlat: 2,
        totalRooms: 9,
        description: "Spectacular duplex penthouse with 360-degree views of Palm Jumeirah and Arabian Gulf. Ultra-luxury living with private rooftop terrace, infinity pool, and bespoke interiors.",
        heroImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&h=600&fit=crop",
        features: [
            "360° Views",
            "Private Rooftop Pool",
            "Elevator Access",
            "Italian Kitchen",
            "Wine Cellar",
            "Cinema Room",
            "Panic Room",
            "4 Parking Spaces"
        ]
    },
    11: {
        id: 11,
        title: "Spacious Family Villa",
        type: "Villa",
        status: "New",
        price: "6,200,000",
        location: "Arabian Ranches, Dubai",
        fullAddress: "Arabian Ranches, Mirador",
        bedrooms: 4,
        bathrooms: 3,
        area: "3,000",
        areaUnit: "sq ft",
        floor: "Ground + 1",
        floorsInFlat: 2,
        totalRooms: 7,
        description: "Perfect family villa in child-friendly community. Spacious layout with large garden, community pool access, and close to schools, parks, and retail centers.",
        heroImage: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1200&h=600&fit=crop",
        features: [
            "Large Garden",
            "Community Pool",
            "Near Schools",
            "Play Area",
            "Modern Kitchen",
            "Family Room",
            "Maid's Room",
            "3-Car Garage"
        ]
    },
    12: {
        id: 12,
        title: "Designer Studio Loft",
        type: "Apartment",
        status: "",
        price: "1,800,000",
        location: "Downtown Dubai, UAE",
        fullAddress: "Downtown Dubai, DIFC District",
        bedrooms: 1,
        bathrooms: 1,
        area: "850",
        areaUnit: "sq ft",
        floor: "15th Floor",
        floorsInFlat: 1,
        totalRooms: 2,
        description: "Stylish studio loft in the heart of DIFC. Perfect for young professionals, featuring high ceilings, modern design, and walking distance to Dubai Mall and Metro.",
        heroImage: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=600&fit=crop",
        features: [
            "High Ceilings",
            "Open Plan Layout",
            "Modern Bathroom",
            "Built-in Wardrobes",
            "Gym & Pool",
            "Near Metro",
            "24/7 Security",
            "Parking Included"
        ]
    }
};

// Function to get property by ID
function getPropertyById(id) {
    return propertiesData[id] || null;
}

// Function to get all properties
function getAllProperties() {
    return Object.values(propertiesData);
}
